services:
  ml:
    container_name: ml
    build: ./ml
    ports:
      - "8000:8000"
  app:
    container_name: app
    build: ./backend
    volumes:
      - /app/instance
    ports:
      - "5005:5005"
    depends_on:
      - ml
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - app